Implement monitoring of new emails
LinusS1/email-skill pull request #8
Opened 2018-12-07 21:31 UTC by Dragoncraft89

This PR implements notifications of unread emails.
The emails are marked as seen when discovered, because you would not want to be notified every minute that there is new mail. The default check my email intent will not mark them as seen.

The monitoring is implemented via repeating events and will therefore look for new mail every 60 seconds.

When stopping mycroft and reopening again, the notification settings are preserved and the skill will continue to look for new mail if it was instructed to do so.

It's also possible to supplement an email-address and the skill will only notify of emails by that sender. However you have to speak very clearly to get a good speech to text translation.

Signed-off-by: florian <floriankothmeier@web.de>

2018-12-09 21:22 UTC, LinusSkucas commented
Thanks for the pr! I'm busy right now trying to squash some bugs with the email skill, but once I get those done, I'll look over this.

Thanks!

2018-12-20 03:49 UTC, LinusSkucas requested changes
Alrighty! Thanks for waiting and submitting the pr!
I left some comments inline but mainly:

 - For all of the skill I use Padatious and would like to keep it unified.
   - This mainly entails combining all the utterances into `.dialog` files and switching to intent_file_handler in `__init__.py`
 - Your way of handling this was good, but the ability to specify names like: `Hey Mycroft, tell me when I get an email from bob` is what I had in mind. We can just use the sender name - we don't need to collect an address book here.
 - Also going off of above - the polling feature is not what I had in mind ( I thought that it would be like the above) and it adds quite a bit of extra code. But, tell me what you think about whether it should be kept. :smile:

Thanks so much for doing this! :smile:

2018-12-20 03:49 UTC, LinusSkucas commented on __init__.py
> +EMAIL_POLL_INTERVAL = 60 # in seconds
This seems like such a short time: maybe 2 min (120 sec)
```suggestion
EMAIL_POLL_INTERVAL = 120 # in seconds
```

2018-12-20 03:49 UTC, LinusSkucas commented on __init__.py
> +        if self.settings.get('look_for_mail'):
This will start a repeating event every time the skill is started up.
Lets put this in a initialize method, so that it only run on startup. -> also consider deleting any other repeating event s before that.

2018-12-20 03:49 UTC, LinusSkucas commented on __init__.py
> +        password = self.settings.get('password')
This line turned out to be the bug that held me back when I was reviewing -> move line 102 to after line 93

2018-12-20 09:49 UTC, Dragoncraft89 commented
1. It's not possible to collect arguments with intent_file_handlers, e.g. "tell me when I get an email from **bob**" is impossible without intent builders
2. Will change that so it can accept emails and sender names. They should be matched case insensitive and when it's part of a name, e.g. Bob Smith will be matched by bob.
3. What is your preferred method for doing that? I don't know of another way than polling.

I don't know when I'll be able to do this, but will probably start working on this tomorrow.

2018-12-21 04:11 UTC, LinusS1 commented
Thanks for responding.
1) Yes it is:
In a .intent file:
`tell me when I get email from {name}`
Then, in the intent:
`name = message.data.get("name")`
2) The fuzzy matching method might help with this: [Mycroft Core docs](https://mycroft-core.readthedocs.io/en/master/source/mycroft.util.parse.html#match-one)
3) Sorry for not making this clear - polling is a great way to find unread email - I just didn't think about enabling polling and having an intent for that - just about `tell me when I have email from bob` without the enable polling intents

2018-12-21 15:12 UTC, Dragoncraft89 commented on __init__.py
> +        if self.settings.get('look_for_mail'):
Where should I put it that it is only run on startup? I thought __init__ is only run on startup?

2018-12-21 17:04 UTC, Dragoncraft89 commented
I hope I addressed most of your concerns.

However I still could not figure out how you expected the intent to work?

2018-12-21 17:20 UTC, Dragoncraft89 commented on __init__.py
> +        if self.settings.get('look_for_mail'):
Nvm, just found out about `initialize()`

2018-12-21 23:28 UTC, LinusSkucas commented
All right, thanks for making those changes. I was just thinking to **delete** the enable and disable polling intents and just having `tell me when I have email from bob` as the monitoring.

Do you think that this would be okay just to have the notification from name?

2018-12-22 09:44 UTC, Dragoncraft89 commented
If you've only got `tell me when I have email from bob`, how would you turn it off, if you don't want to be notified anymore?

2018-12-22 16:04 UTC, LinusS1 commented
Oh, sorry I forgot about that.
Keep the intents - just take out the parts of looking for all new messages.

Thanks!

2018-12-22 20:57 UTC, Dragoncraft89 commented
I'd like to get notified of every email (I get very few mail).

What is the reason you want it removed? If you'd want it to be more explicit (e.g. `Hey mycroft, look for **all** new mail`), that would be possible too.

2018-12-23 01:00 UTC, LinusS1 commented
Okay, thanks I'll merge this now, but I'm going to merge it into a feature branch, because I want to clean a few things up before I upload it to the skill store.

Thanks again for this!

2018-12-23 01:00 UTC, LinusSkucas approved these changes

2018-12-23 01:01 UTC, merged